### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Linear:         size mismatch for weight: copying a param with shape torch.Size([1024, 26400]) from checkpoint, the shape in current model is torch.Size([1024, 12800]).

### ISSUE THREAD

**Issue by Zxl1556180489** [JacobYuan7/DIN-Group-Activity-Recognition-Benchmark#11]
Traceback (most recent call last):
  File "scripts/train_collective_stage2_dynamic.py", line 58, in <module>
    train_net(cfg)
  File "./train_net_dynamic.py", line 83, in train_net
    model.loadmodel(cfg.stage1_model_path)
  File "./infer_model.py", line 1222, in loadmodel
    self.fc_emb_1.load_state_dict(state['fc_emb_state_dict'])
  File "/home/hi/.conda/envs/lj0.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Linear:
        size mismatch for weight: copying a param with shape torch.Size([1024, 26400]) from checkpoint, the shape in current model is torch.Size([1024, 12800]).

**Comment by Zxl1556180489** [comment]
How to solve this problem?

**Comment by ch-its** [comment]
I am facing the same issue. Were you able to resolve it ??

**Comment by Zxl1556180489** [comment]
yes,  you can contact me via WeChat 15074682652

**Comment by Zxl1556180489** [comment]
> I am facing the same issue. Were you able to resolve it ??

yes, you can contact me via WeChat 15074682652

**Comment by ch-its** [comment]
WeChat isn't available in my region, is there some other way I can contact you??

Or can you explain the solution here itself??

**Comment by Zxl1556180489** [comment]
Hello，it's backbone in infer_model.py, you can step debugging in your code.


    if cfg.backbone == 'inv3':
        self.backbone = MyInception_v3(transform_input=False, pretrained=True)
    elif cfg.backbone == 'vgg16':
        self.backbone = MyVGG16(pretrained=True)
    elif cfg.backbone == 'vgg19':
        self.backbone = MyVGG19(pretrained=True)
    elif cfg.backbone == 'res18':
        self.backbone = MyRes18(pretrained=True)
    elif cfg.backbone == 'alex':
        self.backbone = MyAlex(pretrained=True)
    elif cfg.backbone == 'mobilenet':
        self.backbone = MyMobileNet(pretrained=True)
    else:
        assert False

    # START: Original code by Zijian and Xinran
    if cfg.backbone == 'inv3':
        self.fc_emb_1 = nn.Linear(K * K * D, NFB)
    elif cfg.backbone == 'res18':
        self.fc_emb_1 = nn.Linear(12800, NFB)
    elif cfg.backbone == 'vgg16':
        self.fc_emb_1 = nn.Linear(12800, NFB)
    elif cfg.backbone == 'vgg19':
        self.fc_emb_1 = nn.Linear(12800, NFB)
    elif cfg.backbone == 'alex':
        self.fc_emb_1 = nn.Linear(6400, NFB)
    elif cfg.backbone == 'mobilenet':
        self.fc_emb_1 = nn.Linear(32000, NFB)
    # END: Original code by Zijian and Xinran

    self.nl_emb_1 = nn.LayerNorm([NFB])
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JacobYuan7/DIN-Group-Activity-Recognition-Benchmark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月16日(星期三) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JacobYuan7/DIN-Group-Activity-Recognition-Benchmark] RuntimeError: Error(s) in loading state_dict for Linear:         size mismatch for weight: copying a param with shape torch.Size([1024, 26400]) from checkpoint, the shape in current model is torch.Size([1024, 12800]). (Issue #11)





 
WeChat isn't available in my region, is there some other way I can contact you??
 
Or can you explain the solution here itself??
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Snipaste_2022-03-17_15-58-20.png (10.3K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6663323290efcc9a3a0df36e1539014a56050707565b51001e5550010a14075756051f50035b51480b0153045158065450540402331933365d0a4253404d563a015300001e09004802546d030614065d1e51021c435754650e&t=exs_ftn_download&code=3c22393e




Snipaste_2022-03-17_15-59-29.png (9.8K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6d656463abbbcf9e310ba53f1063024e0a01565a0105045215045d53014e04510a5449020154044c0e545705005300035955055b36433032560c14024517553e0a5556511b53034c09523b52034e055815575d4d460d576105&t=exs_ftn_download&code=8edc6c0a
