### ISSUE TITLE
How to set up HRNet-w32 of the TCE inference module?

### ISSUE THREAD

**Issue by 0shelter0** [JacobYuan7/DIN-Group-Activity-Recognition-Benchmark#12]
Hi, thanks for your sharing code of _Learning Visual Context for Group Activity Recognition_. But I get into a trouble with failing to `from hrnet.init_hrnet import cls_hrnet_w32, pose_hrnet_w32` as shown in [`infer_module/TCE_STBiP_module.py`](https://github.com/JacobYuan7/DIN-Group-Activity-Recognition-Benchmark/blob/main/infer_module/TCE_STBiP_module.py). Could you give me some help to solve it?

Additionally, I have another confusion. The construction and usage of HRNet-w32 in your code as follows:
```python
# consturction
if pose_net == 'pose_hrnet_w32':
            self.encoder = pose_hrnet_w32(pretrained=True)


# usage
roi_image = roi_image.cuda()
#print(roi_image.shape) #torch.Size([72, 3, 256, 192])
roi_pose_feature = self.encoder(roi_image)
```
As known, the HRNet-w32 output heatmaps at `final_layer` containing information of all keypoints. However, you get individual features of $d_e$-dimension from HRNet-w32 finally as mentioned in paper, so I want to know how you convert the heatmaps to a feature vector of  $d_e$-dimension for $i$-th person(or bounding box) at certain frame.

I hope to hear from you. Thank you in advance!

Regard

**Comment by 0shelter0** [comment]
Hello, could you make your `TCE_STBiP_module` fully available?  We will thank your for providing entire project master of paper _Learning Visual Context for Group Activity Recognition_.

Thanks for your contribution to this area.

**Comment by 0shelter0** [comment]
Hello, could you make your `TCE_STBiP_module` fully available?  We will thank your for providing entire project master of paper _Learning Visual Context for Group Activity Recognition_.

Thanks for your contribution to this area.

**Comment by JacobYuan7** [comment]
> Hello, could you make your `TCE_STBiP_module` fully available? We will thank your for providing entire project master of paper _Learning Visual Context for Group Activity Recognition_.
> 
> Thanks for your contribution to this area.

I am sorry that I missed this question somehow. The codes for TCE and STBiP were available under _infer_modules_.

**Comment by 0shelter0** [comment]
Thank you all the time, don't be serious for this, I will try my best to make it.
