### ISSUE TITLE
Generating annotations from saved model

### ISSUE THREAD

**Issue by ch-its** [JacobYuan7/DIN-Group-Activity-Recognition-Benchmark#13]
How can I generate annotations for input videos using a saved model without losing out on accuracy ??

**Comment by JacobYuan7** [comment]
> How can I generate annotations for input videos using a saved model without losing out on accuracy ??

Hi, thanks for your interest in our work, but I do not understand your question. Would you mind rephrasing it to make it clearer?

**Comment by ch-its** [comment]
Thanks for replying. I was asking how I could generate activity labels for a given video sequence using a saved model. It's sorted out now. On the other hand, the problem I'm facing now is that when I run the DIN model on Collective Activity Dataset, the accuracy actually decreases. How can I sort that out ??

**Comment by JacobYuan7** [comment]
> Thanks for replying. I was asking how I could generate activity labels for a given video sequence using a saved model. It's sorted out now. On the other hand, the problem I'm facing now is that when I run the DIN model on Collective Activity Dataset, the accuracy actually decreases. How can I sort that out ??

CAD is a dataset that easily overfits and encounters performance fluctuation because of the small dataset size. Usually, you need to use early stopping to achieve high performance.
