### ISSUE TITLE
About the visualization

### ISSUE THREAD

**Issue by SatMa34** [JacobYuan7/DIN-Group-Activity-Recognition-Benchmark#17]
Hi Jacob, thanks for your great job!
You draw the heatmaps of group interaction graph and person interaction graph in the paper (figure 5), and i notice that in dynamic_infer_module.py, you also write code to save relation_list for visualize, i wonder how your draw the heatmaps, could you share the scripts?

**Comment by JacobYuan7** [comment]
> Hi Jacob, thanks for your great job! You draw the heatmaps of group interaction graph and person interaction graph in the paper (figure 5), and i notice that in dynamic_infer_module.py, you also write code to save relation_list for visualize, i wonder how your draw the heatmaps, could you share the scripts?

Actually, it is very intuitive. You can try transforming the value to a discrete distribution and try scaling the value to make it distinguishable in the image.

**Comment by JacobYuan7** [comment]
I am closing this issue. Feel free to reopen it if you have further questions.
