### ISSUE TITLE
Cannot run DIN volleyball stage1

### ISSUE THREAD

**Issue by GaEunKim-study** [JacobYuan7/DIN-Group-Activity-Recognition-Benchmark#19]
The volleyball dataset and tracks_normalized.pkl files have been downloaded properly. However, it does not run as follows:

"""
  File "/home/gaeunter/PycharmProjects/pythonProject/DIN-Group-Activity-Recognition-Benchmark/./volleyball.py", line 269, in load_samples_sequence

    actions = np.hstack(actions).reshape([-1, self.num_boxes])

ValueError: cannot reshape array of size 110 into shape (12)
"""

print(actions)
>>> [[7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7]]

print(np.hstack(actions))
>>>[7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7
0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7
7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7]
[1 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1
2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2
7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2 7
7 7 7 7 7 7 7 7 7]

print(len(np.hstack(actions)))
>>>110

What's wrong?

**Comment by JacobYuan7** [comment]
> The volleyball dataset and tracks_normalized.pkl files have been downloaded properly. However, it does not run as follows:
> 
> """ File "/home/gaeunter/PycharmProjects/pythonProject/DIN-Group-Activity-Recognition-Benchmark/./volleyball.py", line 269, in load_samples_sequence
> 
> ```
> actions = np.hstack(actions).reshape([-1, self.num_boxes])
> ```
> 
> ValueError: cannot reshape array of size 110 into shape (12) """
> 
> print(actions)
> 
> > > > [[7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7], [7, 7, 7, 7, 0, 7, 7, 7, 7, 6, 7]]
> 
> print(np.hstack(actions))
> 
> > > > [7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7
> > > > 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7
> > > > 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7 7 7 7 7 0 7 7 7 7 6 7]
> > > > [1 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1
> > > > 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2
> > > > 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2 7 7 7 7 7 7 7 7 7 7 1 2 7
> > > > 7 7 7 7 7 7 7 7 7]
> 
> print(len(np.hstack(actions)))
> 
> > > > 110
> 
> What's wrong?

I never encounter this problem before. Can you provide more information?

**Comment by JacobYuan7** [comment]
I closed this issue since there is no update.

**Comment by Certainguys** [comment]
Hello, I also have a similar problem and would like to ask how you solved it? Thanks.
