### ISSUE TITLE
Optical flow code

### ISSUE THREAD

**Issue by 199943** [JacobYuan7/DIN-Group-Activity-Recognition-Benchmark#21]
Hello author,
 thank you for your wonderful work. Can you tell me how to process two channels of optical flow images using Resnet-18 and where you got the pre-trained model from, I didn't find the right code, can you provide this part of the code?
thanks.

**Comment by JacobYuan7** [comment]
@199943 Hi, I do not use optical flows in this work. However, if you want to use optical flows, you can transform it to 3-channel representations. I think this transformation is rather easy if you want to visualize optical flows. Then, you can adopt ResNet-18.

**Comment by 199943** [comment]
Thanks for the clarification.

**Comment by JacobYuan7** [comment]
@199943  Note that if you transform it to three-channel representations, the ImageNet pre-training for ResNet-18 might not be helpful. This might require further study.

**Comment by 199943** [comment]
OK, thank you very much!
